//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MKVmergeBatcher.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MKVmergeBatcher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add a file number not greater than .
        /// </summary>
        internal static string AddFileNumberNotGreaterThan {
            get {
                return ResourceManager.GetString("AddFileNumberNotGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string AddLabel {
            get {
                return ResourceManager.GetString("AddLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Model.
        /// </summary>
        internal static string AddModel {
            get {
                return ResourceManager.GetString("AddModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Track.
        /// </summary>
        internal static string AddTrack {
            get {
                return ResourceManager.GetString("AddTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add at least a track from file number 0 (input file).
        /// </summary>
        internal static string AddTrackFromFileNumber0 {
            get {
                return ResourceManager.GetString("AddTrackFromFileNumber0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add at least a track or use a custom model.
        /// </summary>
        internal static string AddTrackOrUseCustomModel {
            get {
                return ResourceManager.GetString("AddTrackOrUseCustomModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another instance is currently running. Closing this one..
        /// </summary>
        internal static string AnotherInstanceIsCurrentlyRunning {
            get {
                return ResourceManager.GetString("AnotherInstanceIsCurrentlyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        internal static string AreYouSure {
            get {
                return ResourceManager.GetString("AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure? Current data will be overwritted. Please make a backup of the configuration folder.
        /// </summary>
        internal static string AreYouSurePleaseMakeBackup {
            get {
                return ResourceManager.GetString("AreYouSurePleaseMakeBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio.
        /// </summary>
        internal static string Audio {
            get {
                return ResourceManager.GetString("Audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bat File created. Do you want to clear the queue?.
        /// </summary>
        internal static string BatCreatedClearQueue {
            get {
                return ResourceManager.GetString("BatCreatedClearQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call type not passed.
        /// </summary>
        internal static string CallTypeNotPassed {
            get {
                return ResourceManager.GetString("CallTypeNotPassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot stop queue.
        /// </summary>
        internal static string CannotStopQueue {
            get {
                return ResourceManager.GetString("CannotStopQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please digit model name.
        /// </summary>
        internal static string DigitModelName {
            get {
                return ResourceManager.GetString("DigitModelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue is running. Do you want to stop current job?.
        /// </summary>
        internal static string DoYouWantStopCurrentJob {
            get {
                return ResourceManager.GetString("DoYouWantStopCurrentJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Model.
        /// </summary>
        internal static string EditModel {
            get {
                return ResourceManager.GetString("EditModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Track.
        /// </summary>
        internal static string EditTrack {
            get {
                return ResourceManager.GetString("EditTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elaborated files.
        /// </summary>
        internal static string ElaboratedFiles {
            get {
                return ResourceManager.GetString("ElaboratedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No models generated.
        /// </summary>
        internal static string EmptyModelList {
            get {
                return ResourceManager.GetString("EmptyModelList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ErrorJobLabel {
            get {
                return ResourceManager.GetString("ErrorJobLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ErrorLabel {
            get {
                return ResourceManager.GetString("ErrorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit code.
        /// </summary>
        internal static string ExitCode {
            get {
                return ResourceManager.GetString("ExitCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original file extension can be specified for additional files (Original file number &gt; 0).
        /// </summary>
        internal static string ExtensionNotRequired {
            get {
                return ResourceManager.GetString("ExtensionNotRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already in queue.
        /// </summary>
        internal static string FileAlreadyInQueue {
            get {
                return ResourceManager.GetString("FileAlreadyInQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import v1 userdata.json.
        /// </summary>
        internal static string ImportV1UserDatajson {
            get {
                return ResourceManager.GetString("ImportV1UserDatajson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string InfoLabel {
            get {
                return ResourceManager.GetString("InfoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please insert the language code.
        /// </summary>
        internal static string InsertLanguageCode {
            get {
                return ResourceManager.GetString("InsertLanguageCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job no longer available. Closing..
        /// </summary>
        internal static string JobNoLongerAvailable {
            get {
                return ResourceManager.GetString("JobNoLongerAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to making a backup.
        /// </summary>
        internal static string MakingBackup {
            get {
                return ResourceManager.GetString("MakingBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Models.
        /// </summary>
        internal static string Models {
            get {
                return ResourceManager.GetString("Models", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moved.
        /// </summary>
        internal static string Moved {
            get {
                return ResourceManager.GetString("Moved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version found. Do you want to open the release page? You can disable the version check in options..
        /// </summary>
        internal static string NewVersionFound {
            get {
                return ResourceManager.GetString("NewVersionFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file to add to queue.
        /// </summary>
        internal static string NoFilesToAddToQueue {
            get {
                return ResourceManager.GetString("NoFilesToAddToQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The mkvmerge location in options is not setted.
        /// </summary>
        internal static string NoMkvMergeLocation {
            get {
                return ResourceManager.GetString("NoMkvMergeLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No jobs to put in Bat file.
        /// </summary>
        internal static string NothingToPutInBat {
            get {
                return ResourceManager.GetString("NothingToPutInBat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing to start.
        /// </summary>
        internal static string NothingToStart {
            get {
                return ResourceManager.GetString("NothingToStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        internal static string Of {
            get {
                return ResourceManager.GetString("Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string OkJobLabel {
            get {
                return ResourceManager.GetString("OkJobLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original file number and position already in track list.
        /// </summary>
        internal static string OriginalFileNumberPositionAlreadyInTrackList {
            get {
                return ResourceManager.GetString("OriginalFileNumberPositionAlreadyInTrackList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        internal static string PendingJobLabel {
            get {
                return ResourceManager.GetString("PendingJobLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process.
        /// </summary>
        internal static string Process {
            get {
                return ResourceManager.GetString("Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process started.
        /// </summary>
        internal static string ProcessStarted {
            get {
                return ResourceManager.GetString("ProcessStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running.
        /// </summary>
        internal static string RunningJobLabel {
            get {
                return ResourceManager.GetString("RunningJobLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save current compiled model?.
        /// </summary>
        internal static string SaveCurrentCompiledModel {
            get {
                return ResourceManager.GetString("SaveCurrentCompiledModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save current track?.
        /// </summary>
        internal static string SaveCurrentTrack {
            get {
                return ResourceManager.GetString("SaveCurrentTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SaveLabel {
            get {
                return ResourceManager.GetString("SaveLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a correct mkvmerge.exe file.
        /// </summary>
        internal static string SelectCorrectMkvmerge {
            get {
                return ResourceManager.GetString("SelectCorrectMkvmerge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select track type.
        /// </summary>
        internal static string SelectTrackType {
            get {
                return ResourceManager.GetString("SelectTrackType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For additional files (Original file number &gt; 0) you must specify at least a suffix or file extension.
        /// </summary>
        internal static string SpecifySuffixOrExtension {
            get {
                return ResourceManager.GetString("SpecifySuffixOrExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtitle.
        /// </summary>
        internal static string Subtitle {
            get {
                return ResourceManager.GetString("Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original file suffix can be specified for additional files (Original file number &gt; 0).
        /// </summary>
        internal static string SuffixNotRequired {
            get {
                return ResourceManager.GetString("SuffixNotRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        internal static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        internal static string SummaryLabel {
            get {
                return ResourceManager.GetString("SummaryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        internal static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please use a different model name. Model is already in list..
        /// </summary>
        internal static string UseDifferentModelName {
            get {
                return ResourceManager.GetString("UseDifferentModelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use only one flag between --no-attachments and Add Attachments.
        /// </summary>
        internal static string UseOneAttachmentFlag {
            get {
                return ResourceManager.GetString("UseOneAttachmentFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserData imported.
        /// </summary>
        internal static string UserDataImported {
            get {
                return ResourceManager.GetString("UserDataImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        internal static string Video {
            get {
                return ResourceManager.GetString("Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string WarningJobLabel {
            get {
                return ResourceManager.GetString("WarningJobLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string WarningLabel {
            get {
                return ResourceManager.GetString("WarningLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working on job.
        /// </summary>
        internal static string WorkingOnJob {
            get {
                return ResourceManager.GetString("WorkingOnJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working on model.
        /// </summary>
        internal static string WorkingOnModel {
            get {
                return ResourceManager.GetString("WorkingOnModel", resourceCulture);
            }
        }
    }
}
